#! /usr/bin/env python
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), os.pardir, 'lib')))
if __name__ == '__main__':
	import ncfv.common
	ncfv.common.main()
